name: augur-qspr-online
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - rdkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - openpyxl
  - xlsxwriter
  - requests
  - pillow
  - plotly
  - python-docx
  - reportlab
  - streamlit
  - pip:
      - streamlit-ketcher==0.0.1
